version: '3'

services:

  backend:
    container_name: backend
    restart: always
    ports:
      - 5001:5001
    build:
      context: ./backend-node
      dockerfile: ./Dockerfile
    volumes:
      - ./backend-node:/code

  couchbase:
    container_name: couchbase
    image: couchbase/server:latest
    ports:
      - 8091-8096:8091-8096
      - 11210:11210
    environment:  
      - CLUSTER_NAME=Cluster
      - COUCHBASE_ADMINISTRATOR_USERNAME=admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=Couchpw
      - COUCHBASE_BUCKET=test
      - COUCHBASE_BUCKET_RAMSIZE=512
      - COUCHBASE_RBAC_USERNAME=admin
      - COUCHBASE_RBAC_PASSWORD=Couchpw
      - COUCHBASE_RBAC_NAME=admin
      - COUCHBASE_RAM_SIZE=2048
      - COUCHBASE_INDEX_RAM_SIZE=512
    hostname: couchbase
    working_dir: /opt/couchbase
    networks:
      - main

networks:
  main:
    driver: bridge
