version: '1'

services:

  influxdb:
      container_name: infdb
      image: influxdb:latest
      ports:
        - '8086:8086'
      volumes:
        - influxdb-storage:/var/lib/influxdb

volumes:

  influxdb-storage: